(() => {
'use strict';
const CATEGORIES=['ポケモンカード','ポケモン関連サプライ用品','釣具','カメラ','レトロゲーム'];
const WEIGHTS={sellability:30,margin:25,profit:15,stability:10,inventoryRisk:10,fees:5,marketTrend:5};
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const clamp=(v,min=0,max=100)=>Math.max(min,Math.min(max,v));
const round=v=>Math.round(num(v));
function normalizeProduct(r={}){return{id:r.id||r.itemId||r.url||`${r.cat||r.category||''}|${r.name||r.title||''}`,name:r.name||r.title||'商品名不明',cat:r.cat||r.category||'その他',cost:num(r.cost),sell:num(r.sell??r.price),ship:num(r.ship??r.shipping),image:r.image||r.imageUrl||'',url:r.url||r.itemWebUrl||'',sold:r.sold==null?null:num(r.sold),list:r.list==null?null:num(r.list),trend:r.trend||'不明',risk:r.risk||'要確認',source:r.source||'eBay',condition:r.condition||'',confidence:r.confidence||null,historicalPrices:Array.isArray(r.historicalPrices)?r.historicalPrices.map(num).filter(v=>v>0):[],soldMedian:num(r.soldMedian),soldHistoryCount:num(r.soldHistoryCount),soldHistoryAvailable:Boolean(r.soldHistoryAvailable)}}
function calcCosts(p,s={}){const fx=Math.max(num(s.fxRate,150),.0001),fee=num(s.feeRate,.136),international=num(s.internationalRate,.0135),fixedUsd=num(s.orderFeeUsd,.4),conv=num(s.conversionFeeRate)/100,dom=num(s.domesticShipping),pack=num(s.packaging),other=num(s.otherCost);const sale=p.sell>0?p.sell:0,ship=p.ship>0?p.ship:0,gross=sale+ship,saleJpy=sale*fx,shipJpy=ship*fx,finalValueFeeJpy=gross*fee*fx,internationalFeeJpy=gross*international*fx,fixedFeeJpy=fixedUsd*fx,conversionFeeJpy=(saleJpy+shipJpy)*conv,localCosts=dom+pack+other,totalFees=finalValueFeeJpy+internationalFeeJpy+fixedFeeJpy+conversionFeeJpy,totalCosts=totalFees+shipJpy+localCosts+p.cost,profit=p.cost>0?round(saleJpy-totalCosts):null,margin=p.cost>0?profit/p.cost:null;return{saleJpy:round(saleJpy),shipJpy:round(shipJpy),finalValueFeeJpy:round(finalValueFeeJpy),internationalFeeJpy:round(internationalFeeJpy),fixedFeeJpy:round(fixedFeeJpy),conversionFeeJpy:round(conversionFeeJpy),localCosts:round(localCosts),totalFees:round(totalFees),totalCosts:round(totalCosts),profit,margin}}
function sellThrough(p){if(p.sold!==null&&p.list!==null&&p.sold>=0&&p.list>=0){const t=p.sold+p.list;return t>0?p.sold/t:null}if(p.soldHistoryAvailable&&p.soldHistoryCount>0)return Math.min(.95,p.soldHistoryCount/Math.max(p.soldHistoryCount+20,1));return null}
function confidence(p){const s=p.soldHistoryAvailable?p.soldHistoryCount:(p.sold||0),l=p.list||0;if(s>=50&&l>=50)return{level:'高',factor:1};if(s>=20&&l>=20)return{level:'中',factor:.94};if(s>=5&&l>=5)return{level:'中',factor:.86};if(p.soldHistoryAvailable&&s>=10)return{level:'中',factor:.88};return{level:'低',factor:(s>0||l>0)?.72:.55}}
function sellabilityScore(p){const r=sellThrough(p);if(r===null)return 10;const count=(p.soldHistoryAvailable?p.soldHistoryCount:0)+(p.list||0)+(p.sold||0),rel=count>=100?1:count>=40?.9:count>=10?.75:.55;return clamp(r*100*rel)}
function trendScore(p){return p.trend==='上昇'?90:p.trend==='横ばい'?70:p.trend==='下落'?25:50}
function stabilityScore(p){const a=p.historicalPrices.map(num).filter(v=>v>0);if(a.length<3)return 50;const avg=a.reduce((x,y)=>x+y,0)/a.length,variance=a.reduce((x,y)=>x+Math.pow(y-avg,2),0)/a.length,cv=avg>0?Math.sqrt(variance)/avg:1;return clamp(100-cv*180)}
function feeScore(p,c){if(p.sell<=0)return 0;return clamp(100-(c.totalFees/Math.max(c.saleJpy,1))*300)}
function marginScore(c){return c.margin===null||c.margin<=0?0:clamp(c.margin*250)}
function profitScore(c,profits=[]){if(c.profit===null)return 0;const pos=profits.filter(v=>Number.isFinite(v)&&v>0),max=pos.length?Math.max(...pos):0;return max&&c.profit>0?clamp(c.profit/max*100):0}
function projectedPrice(p,days){if(p.soldMedian>0){const base=p.soldMedian;return round(base)}let f=p.trend==='上昇'?(days===30?1.01:days===60?1:.98):p.trend==='横ばい'?(days===30?.98:days===60?.96:.94):p.trend==='下落'?(days===30?.93:days===60?.87:.8):(days===30?.97:days===60?.94:.9);const a=p.historicalPrices.map(num).filter(v=>v>0);if(a.length>=3){const change=a[0]>0?(a[a.length-1]-a[0])/a[0]:0;f*=clamp(1+change*(days/90),.65,1.15)}return round(Math.max(p.sell,0)*f)}
function breakEvenPrice(p,s={}){const fx=Math.max(num(s.fxRate,150),.0001),variable=num(s.feeRate,.136)+num(s.internationalRate,.0135),fixed=num(s.orderFeeUsd,.4)*fx,local=num(s.domesticShipping)+num(s.packaging)+num(s.otherCost),d=1-variable;return p.cost>0&&d>0?round((p.cost+local+fixed)/d):null}
function simulateRisk(p,s={}){const scenarios=[30,60,90].map(days=>{const sale=projectedPrice(p,days),c=calcCosts({...p,sell:sale},s);const risk=c.profit===null?'要仕入価格':c.profit<0?'高':c.margin!==null&&c.margin<.1?'高':c.margin!==null&&c.margin<.2?'中':'低';return{days,sale,profit:c.profit,margin:c.margin,risk}});return{scenarios,breakEven:breakEvenPrice(p,s)}}
function inventoryRiskScore(r,p){let x=100,s=r.scenarios;if(p.cost<=0)return 45;if(s[0].profit<0)x-=60;else if(s[0].profit<p.cost*.1)x-=30;if(s[1].profit<0)x-=25;else if(s[1].profit<p.cost*.1)x-=12;if(s[2].profit<0)x-=25;else if(s[2].profit<p.cost*.1)x-=12;if(p.cost>50000)x-=10;return clamp(x)}
function riskFlags(p,c,r){const a=[];if(!p.soldHistoryAvailable&&p.sold===null)a.push('販売実績データ不足');if(p.cost<=0)a.push('仕入価格未入力');if(p.trend==='下落')a.push('相場下落傾向');if(c.profit!==null&&c.profit<0)a.push('現在価格でも赤字');if(r.scenarios[2].profit!==null&&r.scenarios[2].profit<0)a.push('90日後想定で赤字');if(p.cost>=50000)a.push('高額仕入れ');if(p.soldHistoryAvailable)a.push(`過去90日販売データ：${p.soldHistoryCount}件`);return a}
function scoreProduct(raw,s={},universe=[]){const p=normalizeProduct(raw),c=calcCosts(p,s),profits=universe.map(x=>calcCosts(normalizeProduct(x),{...s,feeRate:s.feeRateByCategory?.[normalizeProduct(x).cat]??s.feeRate}).profit).filter(v=>v!==null),r=simulateRisk(p,s),scores={sellability:sellabilityScore(p),margin:marginScore(c),profit:profitScore(c,profits),stability:stabilityScore(p),inventory:inventoryRiskScore(r,p),fees:feeScore(p,c),market:trendScore(p)},conf=confidence(p);let total=(scores.sellability*.3+scores.margin*.25+scores.profit*.15+scores.stability*.1+scores.inventory*.1+scores.fees*.05+scores.market*.05)*conf.factor;const flags=riskFlags(p,c,r);if(flags.includes('現在価格でも赤字'))total-=25;if(flags.includes('90日後想定で赤字'))total-=12;if(flags.includes('相場下落傾向'))total-=8;total=round(clamp(total));const stars=total>=90?'★★★★★':total>=80?'★★★★☆':total>=70?'★★★★☆':total>=60?'★★★☆☆':total>=50?'★★☆☆☆':'★☆☆☆☆',risk=flags.includes('現在価格でも赤字')||flags.includes('90日後想定で赤字')?'高':scores.inventory>=75?'低':scores.inventory>=50?'中':'高';return{...p,costs:c,riskData:r,scores,totalScore:total,stars,risk,confidence:conf.level,flags}}
function rank(products,s={},category=null){const n=products.map(normalizeProduct),base={...s,feeRateByCategory:s.feeRateByCategory||{}},src=category?n.filter(p=>p.cat===category):n;return src.map(p=>scoreProduct(p,{...base,feeRate:base.feeRateByCategory[p.cat]??base.feeRate},n)).sort((a,b)=>b.totalScore-a.totalScore||(b.costs.profit||-Infinity)-(a.costs.profit||-Infinity)||a.name.localeCompare(b.name,'ja'))}
window.RankingEngine={CATEGORIES,WEIGHTS,normalizeProduct,calcCosts,sellThrough,confidence,simulateRisk,breakEvenPrice,scoreProduct,rank};
})();
